export const CATEGORY_FLAT_REQUEST = 'CATEGORY_FLAT_REQUEST' as const
export const CATEGORY_FLAT_REQUEST_SUCCESS = 'CATEGORY_FLAT_REQUEST_SUCCESS' as const
export const CATEGORY_FLAT_REQUEST_ERROR = 'CATEGORY_FLAT_REQUEST_ERROR' as const

export const CATEGORY_TREE_REQUEST = 'CATEGORY_TREE_REQUEST' as const
export const CATEGORY_TREE_REQUEST_SUCCESS = 'CATEGORY_TREE_REQUEST_SUCCESS' as const
export const CATEGORY_TREE_REQUEST_ERROR = 'CATEGORY_TREE_REQUEST_ERROR' as const
