export const CATEGORY_FLAT_REQUEST = 'CATEGORY_FLAT_REQUEST';
export const CATEGORY_FLAT_REQUEST_SUCCESS = 'CATEGORY_FLAT_REQUEST_SUCCESS';
export const CATEGORY_FLAT_REQUEST_ERROR = 'CATEGORY_FLAT_REQUEST_ERROR';

export const CATEGORY_TREE_REQUEST = 'CATEGORY_TREE_REQUEST';
export const CATEGORY_TREE_REQUEST_SUCCESS = 'CATEGORY_TREE_REQUEST_SUCCESS';
export const CATEGORY_TREE_REQUEST_ERROR = 'CATEGORY_TREE_REQUEST_ERROR';
