export const FILE_LIST_BY_POST_REQUEST = "FILE_LIST_BY_POST_REQUEST" as const
export const FILE_LIST_BY_POST_REQUEST_SUCCESS = "FILE_LIST_BY_POST_REQUEST_SUCCESS" as const
export const FILE_LIST_BY_POST_REQUEST_ERROR = "FILE_LIST_BY_POST_REQUEST_ERROR" as const
