export const POST_SEARCH_REQUEST = 'POST_SEARCH_REQUEST' as const
export const POST_SEARCH_REQUEST_SUCCESS = 'POST_SEARCH_REQUEST_SUCCESS' as const
export const POST_SEARCH_REQUEST_ERROR = 'POST_SEARCH_REQUEST_ERROR' as const

export const POST_LOAD_FOR_MODIFY_REQUEST = 'POST_LOAD_FOR_MODIFY_REQUEST' as const
export const POST_LOAD_FOR_MODIFY_REQUEST_SUCCESS = 'POST_LOAD_FOR_MODIFY_REQUEST_SUCCESS' as const
export const POST_LOAD_FOR_MODIFY_REQUEST_ERROR = 'POST_LOAD_FOR_MODIFY_REQUEST_ERROR' as const

export const POST_LOCAL_MODIFY_SUBJECT = 'POST_LOCAL_MODIFY_SUBJECT' as const
export const POST_LOCAL_MODIFY_SUBJECT_SUCCESS = 'POST_LOCAL_MODIFY_SUBJECT_SUCCESS' as const
export const POST_LOCAL_MODIFY_CATEGORY_ID = 'POST_LOCAL_MODIFY_CATEGORY_ID' as const
export const POST_LOCAL_MODIFY_CATEGORY_ID_SUCCESS = 'POST_LOCAL_MODIFY_CATEGORY_ID_SUCCESS' as const
export const POST_LOCAL_MODIFY_BODY = 'POST_LOCAL_MODIFY_BODY' as const
export const POST_LOCAL_MODIFY_BODY_SUCCESS = 'POST_LOCAL_MODIFY_BODY_SUCCESS' as const
export const POST_LOCAL_MODIFY_PUBLIC = 'POST_LOCAL_MODIFY_PUBLIC' as const
export const POST_LOCAL_MODIFY_PUBLIC_SUCCESS = 'POST_LOCAL_MODIFY_PUBLIC_SUCCESS' as const
