export const POST_SEARCH_REQUEST = 'POST_SEARCH_REQUEST';
export const POST_SEARCH_REQUEST_SUCCESS = 'POST_SEARCH_REQUEST_SUCCESS';
export const POST_SEARCH_REQUEST_ERROR = 'POST_SEARCH_REQUEST_ERROR';
