export const POST_SINGLE_SEARCH_REQUEST = 'POST_SINGLE_SEARCH_REQUEST';
export const POST_SINGLE_SEARCH_REQUEST_SUCCESS = 'POST_SINGLE_SEARCH_REQUEST_SUCCESS';
export const POST_SINGLE_SEARCH_REQUEST_ERROR = 'POST_SINGLE_SEARCH_REQUEST_ERROR';


