export const USER_LOGIN_ERROR_MESSAGE = "USER_LOGIN_ERROR_MESSAGE"
export const USER_LOGIN_ERROR_MESSAGE_SUCCESS = "USER_LOGIN_ERROR_MESSAGE_SUCCESS"

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_REQUEST_SUCCESS = "LOAD_USER_REQUEST_SUCCESS"
export const LOAD_USER_REQUEST_ERROR = "LOAD_USER_REQUEST_ERROR"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_REQUEST_SUCCESS = "USER_LOGIN_REQUEST_SUCCESS"
export const USER_LOGIN_REQUEST_ERROR = "USER_LOGIN_REQUEST_ERROR"

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST"
export const USER_LOGOUT_REQUEST_SUCCESS = "USER_LOGOUT_REQUEST_SUCCESS"
export const USER_LOGOUT_REQUEST_ERROR = "USER_LOGOUT_REQUEST_ERROR"
