export const USER_LOGIN_ERROR_MESSAGE = "USER_LOGIN_ERROR_MESSAGE"
export const USER_LOGIN_ERROR_MESSAGE_SUCCESS = "USER_LOGIN_ERROR_MESSAGE_SUCCESS"

export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"

export const USER_LOGOUT = "USER_LOGOUT"
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR"
