export const USER_LOGIN_ERROR_MESSAGE = "USER_LOGIN_ERROR_MESSAGE" as const
export const USER_LOGIN_ERROR_MESSAGE_SUCCESS = "USER_LOGIN_ERROR_MESSAGE_SUCCESS" as const

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST" as const
export const LOAD_USER_REQUEST_SUCCESS = "LOAD_USER_REQUEST_SUCCESS" as const
export const LOAD_USER_REQUEST_ERROR = "LOAD_USER_REQUEST_ERROR" as const

export const SERVER_LOAD_USER_REQUEST_SUCCESS = "SERVER_LOAD_USER_REQUEST_SUCCESS" as const

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST" as const
export const USER_LOGIN_REQUEST_SUCCESS = "USER_LOGIN_REQUEST_SUCCESS" as const
export const USER_LOGIN_REQUEST_ERROR = "USER_LOGIN_REQUEST_ERROR" as const

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST" as const
export const USER_LOGOUT_REQUEST_SUCCESS = "USER_LOGOUT_REQUEST_SUCCESS" as const
export const USER_LOGOUT_REQUEST_ERROR = "USER_LOGOUT_REQUEST_ERROR" as const
