import Head from "next/head";

export default function MetaHeader({children, ...props}) {
    return (
        <Head>
            <title>Skyscape</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}